# Site settings
title: "WCEC English Ministry"
url: "http://h313.github.io/"
baseurl: "wcec-em"

# Contact
phone: "(302) 239-4990"
email: "hello@garrettboatman.com"

# Use this for production
#sass:
#    style: :compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
